[build]
  # Use our build script that bypasses TypeScript errors
  command = "npm run build:no-types"
  publish = "dist"
  
[build.environment]
  # Specify Node.js version explicitly
  NODE_VERSION = "18"
  
# Set environment variables for production
[context.production.environment]
  VITE_API_URL = "https://authentic-reader-api-8b0a83fb7d96.herokuapp.com/api"
  VITE_BACKEND_URL = "https://authentic-reader-api-8b0a83fb7d96.herokuapp.com"
  # Disable ChromaDB in production as it's not available
  VITE_ENABLE_CHROMA = "false"
  VITE_ENABLE_FEEDBACK_LOOP = "false"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 